spring:
  application:
    name: spring.kafka.producer
  kafka:
    bootstrap-servers: localhost:9092

server:
  port: 9090

batch:
  size: 25000

topic:
  send:
    csv:
      consumer: "topic.csv.consumer"
      kafka: "topic.csv.kafka"